# Perfil Docker - usa serviços do docker-compose
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/imovelconecte
    username: imovelconecte
    password: imovelconecte
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
